name: Majestic Homes
markdown: redcarpet
highlighter: rouge
phone_number: 519-729-2728
email: info@majestichomes.ca
mailing_address: 55 Newcastle Drive Kitchener, ON N2R 1X2
blue: "#002366"
gold: "#cfb550"
testimonial_columns: 2